### ISSUE TITLE
Whisper parameter tweaks for hallucinations / ghosting

### ISSUE THREAD

**Issue by Karrde1984** [sandrohanea/whisper.net#102]
Hi
There are some discussions about those ghost transcriptions with whisper and there are some parameter tweaks around, which reduces those hallucinations by ~90%. The most important parameter is called „condition_on_previous_text“.  But that parameter is nowhere to see in whisper.net.
Can you include that parameter anytime soon? I think it is highly important

You can follow the discussion about that topic here:
https://github.com/openai/whisper/discussions/679

What do you mean?

**Comment by sandrohanea** [comment]
Unfortunately, that parameter is not added in https://github.com/ggerganov/whisper.cpp/tree/master and this library is a wrapper for whisper.cpp.

If that option would be added there, it will be added in this library as well automatically in order to update to latest version, but for now, there is not much we can do here.

**Comment by Karrde1984** [comment]
Thanks for your answer. So i will ask the question @ whisper.cpp as well, as it is very important parameter setting. it reduces those hallucinations heavily and we cant see any relevant negativ side effects.

**Comment by lmxin123** [comment]
If you don't have this parameter, have you solved your hallucination problem so far? I often encounter hallucination problems and haven't found a solution yet

@Karrde1984
