### ISSUE TITLE
Switching between CPU and GPU at runtime

### ISSUE THREAD

**Issue by AshD** [sandrohanea/whisper.net#114]
I am writing a Windows WPF desktop x64 app. 

How do I switch between Whisper.net.Runtime and Whisper.net.Runtime.Clblast, if the end user has a GPU or not.

Is there a way that Whisper.net can dynamically switch and choose the best runtime for performance after checking if it's a Nvidia, AMD or no GPU present?

Thanks,
Ash

**Comment by sandrohanea** [comment]
Hello @AshD,
Currently this thing is not supported.

In order to create such a thing, the loader + some new package which includes all runtimes needs to be created.

**Comment by AshD** [comment]
Thanks Sandro. I can test this when it is ready.

The LlamaSharp team did something similar by trying to load different Llama.cpp dlls starting with Cuda12, Cuda11 to CPU variants. 
https://github.com/SciSharp/LLamaSharp/commit/10678a83d622e5b7cb5355e42486c24f74cdad4a

**Comment by lilhoser** [comment]
+1

**Comment by dfengpo** [comment]
+1

**Comment by sandrohanea** [comment]
This is now finally possible with https://github.com/sandrohanea/whisper.net/tree/fc1282f9a92f03e854a66c65b39ef2c9dfdc23e4?tab=readme-ov-file#multiple-runtimes-support.

Be sure you upgrade to minimum 1.7.0 and you can reference multple runtimes in the same project and define an order for loading (or just use the default order). 

If the platform is available, it will be used, otherwise, it will load the next one.
