### ISSUE TITLE
How to Select GPU in C# code?

### ISSUE THREAD

**Issue by yzxJerry** [sandrohanea/whisper.net#182]
My computer have 2 GPUs，how to set or select GPU1 to run?

**Comment by dfengpo** [comment]
I also want to know

**Comment by carterlist** [comment]
Install Whisper.net.Runtime.Cublas package
Uninstall  Whisper.net.Runtime package if installed
 
 initialize factory like so
using var whisperFactory = WhisperFactory.FromPath(_whisperBaseModel, useGpu: true);  //add gpu parameter

**Comment by sandrohanea** [comment]
> My computer have 2 GPUs，how to set or select GPU1 to run?


For cases where you have multiple GPU devices and you want to pick a specific one to be used, you can do this (starting with 1.7.0)

```
RuntimeOptions.Instance.SetGpuDevice(device: 1)
```
See: https://github.com/sandrohanea/whisper.net/blob/main/Whisper.net/LibraryLoader/RuntimeOptions.cs#L65C17-L65C29


> Install Whisper.net.Runtime.Cublas package Uninstall Whisper.net.Runtime package if installed
> 
> initialize factory like so using var whisperFactory = WhisperFactory.FromPath(_whisperBaseModel, useGpu: true); //add gpu parameter

Now we also support multiple runtimes in the same project, and you don't need to uninstall Whisper.net.Runtime package: https://github.com/sandrohanea/whisper.net/tree/main?tab=readme-ov-file#multiple-runtimes-support

Cuda will be used if it is available and can be loaded, otherwise will fallback to CPU.
