### ISSUE TITLE
System.IO.FileNotFoundException: Native Library not found in default paths.Verify you have have included the native Whisper library in your application, or install the default libraries with the Whisper.net.Runtime NuGet.

### ISSUE THREAD

**Issue by ZeeLyn** [sandrohanea/whisper.net#233]
There is no problem in the local development environment. Published on the Windows server and throw an exception:
System.IO.FileNotFoundException: Native Library not found in default paths.Verify you have have included the native Whisper library in your application, or install the default libraries with the Whisper.net.Runtime NuGet.

**Comment by sandrohanea** [comment]
Sounds like the library couldn't be found or loaded in the Windows Server.
It can be because of multiple reasons: 
 - The server doesn't have AVX support and you only referenced `Whisper.net.Runtime` that requires the AVX instructions => Try to reference `Whisper.net.AllRuntimes` **or** add a new reference to `Whisper.net.Runtime.NoAvx` 
 - You published in some way that `/runtimes` directory was not copied to the output published data => Please, check the structure of the published file on the Windows Server.
 For this, try to execute `Get-ChildItem -Path "." -Recurse` to see if the runtimes are copied there:
 
 It should show something like this:
![image](https://github.com/user-attachments/assets/8ac07cfa-3fb3-44a7-bc07-dfa03e101b1b)

**Comment by ZeeLyn** [comment]
Thank you for your timely reply, find the reason, the CUDA version on the server is less than 12.1

**Comment by sandrohanea** [comment]
Yes, that's another way how library cannot be found (same as AVX example above) if CUDA cannot be loaded and no alternative and compatible runtime is referenced.
