### ISSUE TITLE
Separate prompt per inference call

### ISSUE THREAD

**Issue by Lyrcaxis** [sandrohanea/whisper.net#250]
At the moment the only time you can pass a prompt is while configuring the builder.

This prevents prompting on a per-infer call, for:
- coherent continuation (e.g.: real-time speech with persisting KV cache, even if it has to be reprocessed),
- contextual information (e.g.: "This is a command one of [...]: "), or separate prompts with the same or multiple audios

Is there a reason behind this current architecture?

And, are there any possibilities of seeing a per-infer-call prompt feature in a future version?

**Comment by sandrohanea** [comment]
Hello @Lyrcaxis ,
The idea for the WhisperProcessor is to be a lightweight object that can be created for each inference call (so that you can set language, prompt, etc, for each Processor). 

For this to be possible, the `whisper_context` is actually loaded for the WhisperFactory, so the loaded model, vocabulary, etc. are loaded only once for the WhisperFactory and re-used across multiple WhisperProcessors and inference calls.

Also, from the same WhisperProcessorBuilder, you should be able to create multiple WhisperProcessors, one for each inference call.

Regarding KV cache: that is indeed created and initialized for each `whisper_state` (which is one per WhisperProcessor) and cannot be reused for difference inference calls, but this is afaik by design in whisper.cpp:

https://github.com/ggerganov/whisper.cpp/blob/55e422109b3504d1a824935cc2681ada7ee9fd38/src/whisper.cpp#L837

Please, let me know if you're still thinking it would bring any benefit for using the same WhisperProcessor (and whisper.cpp `whisper_state`) as I might have missed something.

**Comment by Lyrcaxis** [comment]
Hello @sandrohanea and thank you for the detailed response,

> the `whisper_context` is actually loaded for the WhisperFactory, so the loaded model, vocabulary, etc. are loaded only once

I see now, I was missing this important piece of info, thinking `Factory` was just the config! Thanks for clarifying.

With the new info I don't see any value in the feature I mentioned above. For real-world applications without batching the overhead for reprocessing the kv cache would be minimal, and caching it might go beyond the scope of `Whisper.net`.
