### ISSUE TITLE
How to set the usage of graphics card memory？

### ISSUE THREAD

**Issue by dfengpo** [sandrohanea/whisper.net#293]
The 17.3 version use gpu memory 7gb,How to set the usage of graphics card memory?
![image](https://github.com/user-attachments/assets/60f435a2-9673-4f21-afa7-9171a3d1fc6c)

**Comment by sandrohanea** [comment]
Not sure if I undestand the request?
What exactly do you mean to set the usage of the graphics card memory?

**Comment by dfengpo** [comment]
It means running the program in a fixed size in the graphics card storage

**Comment by sandrohanea** [comment]
Thanks for clarifying your request!

The library requires loading the full whisper model into GPU memory to perform the operations efficiently.
Unfortunately, it's not possible to cap or fix the amount of GPU memory usage because the model must reside entirely in memory to take advantage of GPU acceleration. This is internal to whisper.cpp and not a constraint on whisper.net.


Using a smaller version of the model will use less memory but in order to load a specific model, you'll need specific amount of memory.
