### ISSUE TITLE
I hope this project can support .net framework 4.7.2

### ISSUE THREAD

**Issue by futureflsl** [sandrohanea/whisper.net#70]
some times,we have to use winform to develop our software,so .net framework 4.7.2 can be supported,it will be well for winform.

**Comment by sandrohanea** [comment]
Hello @futureflsl ,
This package is already supporting netframework 4.7.2 as it is targeting netstandard 2.0.

In order to have access to the IAsyncEnumerable and Memory, Whisper.net takes a dependency on 2 packages for netstandard2.0.  They are normally automatically resolved if using SDK-style project, but if using the old csproj type, you'll need to manually install them, see more here: https://github.com/sandrohanea/whisper.net/issues/69

**Comment by sandrohanea** [comment]
Also, really recommend having a plan switching to netcore (winforms are also supported on netcore: https://github.com/dotnet/winforms)
